// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-MXa6v3YXwjcvE8V-q7PYl_KtncXJXc',
    appId: '1:160639709055:web:4305465bace0802613f44a',
    messagingSenderId: '160639709055',
    projectId: 'atta-studio-develop',
    authDomain: 'atta-studio-develop.firebaseapp.com',
    storageBucket: 'atta-studio-develop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Ci-dvM37df-IN6DVBhDZYvCUHKsphVU',
    appId: '1:160639709055:android:559248516952071413f44a',
    messagingSenderId: '160639709055',
    projectId: 'atta-studio-develop',
    storageBucket: 'atta-studio-develop.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCRC75LPNTPyr9zONkbgM8nyNZ-0uPT4',
    appId: '1:160639709055:ios:ee7b898f33b6614313f44a',
    messagingSenderId: '160639709055',
    projectId: 'atta-studio-develop',
    storageBucket: 'atta-studio-develop.firebasestorage.app',
    iosBundleId: 'com.atta.merchantAppFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCRC75LPNTPyr9zONkbgM8nyNZ-0uPT4',
    appId: '1:160639709055:ios:ee7b898f33b6614313f44a',
    messagingSenderId: '160639709055',
    projectId: 'atta-studio-develop',
    storageBucket: 'atta-studio-develop.firebasestorage.app',
    iosBundleId: 'com.atta.merchantAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR-MXa6v3YXwjcvE8V-q7PYl_KtncXJXc',
    appId: '1:160639709055:web:1d272132fba56a2413f44a',
    messagingSenderId: '160639709055',
    projectId: 'atta-studio-develop',
    authDomain: 'atta-studio-develop.firebaseapp.com',
    storageBucket: 'atta-studio-develop.firebasestorage.app',
  );
}
